server:
  port: 8087

spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:h2:mem:categories-db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
